services:
  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    ports:
      - '3306:3306'
    networks:
      - app-network
      
  vue:
    build:
      context: ./front
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"

  web:
    image: urnau/app1-php:prod-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    volumes:
      - ./app:/var/www/app
    env_file:
      - ./app/.env
    ports:
      - "80:80" #http
      - "443:443" #https
    depends_on:
      - mysql 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:

